apiVersion: apps/v1
kind: Deployment
metadata:
  name: stackboard-deployment
  labels:
    app: two-tier-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: two-tier-app
  template:
    metadata:
      labels:
        app: two-tier-app
    spec:
      containers:
        - name: stackboard-ctr
          image: 'khushisharma03/flaskapp:latest'
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_PASSWORD
              value: admin
            - name: MYSQL_DATABASE
              value: mydb
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
