apiVersion: v1
kind: Pod
metadata:
  name: stackboard-pod
spec:
  containers:
    - name: stackboard-ctr
      image: 'khushisharma03/flaskapp:latest'
      env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASS
          value: admin
        - name: MYSQL_DB
          value: myDB
      ports:
        - containerPort: 5000
      imagePullPolicy: Always